app/layout.tsx
app/page.tsx

* Redirect after page load
Fix #21

Fix #21 Clean load time warnings

---

package-lock.json
package.json

fix #24 Update to nextjs 14.1

---

README.md

Update README.md - extend the getting started

---

.github/dependabot.yml

Update dependabot.yml add github-action

---

app/api/auth/[...nextauth]/options.ts

when checking the user role catch other errors

Fix #323 throw other errors 

---

app/components/ui/Button.tsx
app/graph/GraphDataPanel.tsx
app/graph/GraphView.tsx
app/graph/page.tsx

and make sure it close after running query and change the scroll from the values to three dots and tooltip

Fix #469 #494 change the data panel component

---

app/components/EditorComponent.tsx

enable history only on first line

Fix #522 fix the cleaning way on collapsed

---

app/api/graph/model.ts
app/graph/View.tsx
app/schema/SchemaView.tsx

Bug fix, Enhancement
___
- Fixed preferences view to handle color updates correctly.
- Enhanced `Graph.create` method with stricter type definitions.
- Improved UI layout and behavior in `View.tsx`.
- Added validation for `addDisabled` in `SchemaView.tsx`.
___
<tr>
<td>
<details>
<summary><strong>model.ts</strong><dd><code>Enhance `Graph.create` method with stricter typing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/api/graph/model.ts
<li>Updated <code>Graph.create</code> method to use stricter type definitions.<br> <li> Improved clarity of the <code>results</code> parameter structure.
</details>
</td>
<td><a …

Fix #604 fix preferences view

---

app/components/EditorComponent.tsx
app/graph/Selector.tsx

- Implement loading indicator for query execution
- Disable submit button during query processing
- Add async handling for query submission
- Use Loader2 icon to show loading state

Fix #703 Add loading state to query submission in EditorComponent

---

app/api/graph/[graph]/[node]/route.ts
app/api/graph/config/route.ts
app/api/graph/model.ts
app/api/schema/[schema]/[node]/route.ts
app/api/schema/route.ts
app/schema/SchemaView.tsx

and move the fetch count call out of the loop

Fix #844 Fix delete

---

app/api/schema/[schema]/[node]/route.ts
app/schema/SchemaCreateElement.tsx
app/schema/SchemaView.tsx

…CreateElement and SchemaView components. Ensure proper validation for labels and selected nodes before creating relations.

Fix #865 Fix create relation

---

app/api/schema/[schema]/route.ts
app/components/graph/DeleteGraph.tsx
app/components/ui/combobox.tsx

…ph component for improved deletion handling

Fix #889 Fix delete schema

---

app/settings/QuerySettings.tsx
e2e/logic/POM/graphPage.ts
e2e/logic/POM/settingsQueryPage.ts
e2e/tests/queryHistory.spec.ts
e2e/tests/settingsQuery.spec.ts

Enhance QuerySettings component with tooltips for Timeout and Limit and improve input handling for infinite values. Adjust button click behavior to prevent negative values.

Fix #898 Enhance QuerySettings component with tooltips for Timeout and Limit

---

app/loginVerification.tsx
app/settings/QuerySettings.tsx

Enhance login and query settings functionality by saving  localstorage persistence for timeout and limit values. Initialize state from localStorage in LoginVerification and update localStorage on timeout and limit adjustments in QuerySettings.

Fix #891 Enhance login and query settings functionality by saving to localStorage

---

app/components/Header.tsx
app/graph/Selector.tsx

- Updated the logic in Header to show the CreateGraph component only on specific routes.
- Removed the CreateGraph component from Selector.
- Improved code readability and maintainability by consolidating conditional rendering.

Fix #932 Refactor Header component to conditionally render CreateGraph and remove from Selector component

---

app/api/graph/model.ts
app/components/CreateGraph.tsx
app/components/EditorComponent.tsx
app/components/ForceGraph.tsx
app/components/provider.ts
app/components/ui/combobox.tsx
app/graph/GraphView.tsx
app/graph/MetadataView.tsx
app/graph/Selector.tsx
app/graph/controls.tsx
app/graph/labels.tsx
app/graph/page.tsx
app/graph/toolbar.tsx
app/providers.tsx
app/schema/SchemaCreateElement.tsx
app/schema/SchemaDataPanel.tsx
app/schema/SchemaView.tsx
app/schema/page.tsx
lib/utils.ts

- Introduced SchemaContext, SchemaNameContext, and SchemaNamesContext to manage schema-related state.
- Updated NextAuthProvider to include schema state management alongside existing graph state.
- Refactored components to utilize new schema contexts, ensuring consistent data flow.
- Added HistoryQuery and Query types to model schema query history and current query state.
- Improved Graph class to handle currentQuery state, enhancing graph data management.
- Adjusted various components to integrate schema data handling, improving overall functionality.

Fix #937 Enhance Graph and Schema Contexts with New State Management

---

app/components/TableComponent.tsx
app/graph/selectGraph.tsx
app/settings/Configurations.tsx
app/settings/users/Users.tsx

Update usages in Configurations and Users components to pass entityName prop. Adjust DialogContent height in SelectGraph for better layout.

Fix #972 Enhance TableComponent to support dynamic entity names for search placeholder.

---

app/api/graph/[graph]/count/route.ts
app/api/schema/[schema]/count/route.ts
app/components/EditorComponent.tsx

add clear button in the editor for better user experience.

Fix #951 Enhance EditorComponent functionality.

---

app/components/EditorComponent.tsx
app/graph/Selector.tsx

and adjust Selector component height for improved UI consistency.

Fix #951 Refactor EditorComponent layout to group buttons

---

app/settings/page.tsx

Use a named function for event handling and ensure proper cleanup on component unmount.

Fix #953 Refactor Escape key listener in Settings component to improve readability and maintainability.

---

app/api/graph/[graph]/suggestions/route.ts
app/components/ForceGraph.tsx

Reverts FalkorDB/falkordb-browser#1078
___
Other
___
- Reverts ForceGraph component enhancements and link rendering improvements
- Removes index type from graph suggestions API
- Restores original link styling and hover behavior
- Eliminates custom link drawing and arrow length logic
___
```mermaid
flowchart LR
A["Enhanced ForceGraph"] -- "revert changes" --> B["Original ForceGraph"]
C["API with index type"] -- "remove index" --> D["API without index"]
E["Custom link rendering"] -- "restore default" --> F["Standard link rendering"]
```
<tr>
<td>
<details> …

Revert "Fix # 1077 Enhance ForceGraph component with improved link rendering and hover e…"

---

app/components/EditorComponent.tsx
app/graph/GraphDetails.tsx
app/graph/GraphView.tsx
app/graph/Selector.tsx
app/graph/page.tsx
app/schema/SchemaView.tsx
app/schema/page.tsx

Bug fix, Enhancement
___
- Fix count display in graph details with loading states
- Refactor loading state management across components
- Make node/edge counts optional with spinner fallback
- Improve query execution state handling
___
```mermaid
flowchart LR
A["Page Component"] --> B["Query Loading State"]
B --> C["EditorComponent"]
B --> D["Selector"]
A --> E["Count Fetching"]
E --> F["GraphDetails"]
F --> G["Loading Spinner"]
E --> H["Optional Counts"]
```
<tr>
<td>
<details>
<summary><strong>EditorComponent.tsx</strong><dd><code>Externalize query loading state management</code>&nbsp; &nbsp; …

Fix #1074 Fix count in graph details

---

package-lock.json
package.json

Other
___
- Update package version from 1.4.2 to 1.4.3
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Version bump to 1.4.3</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
- Update version field from "1.4.2" to "1.4.3"
</details>
</td>
<td><a href="https://github.com/FalkorDB/falkordb-browser/pull/1102/files#diff-7ae45ad102eab3 …

Update version to 1.4.3 in package.json and package-lock.json

---

app/components/TableComponent.tsx

…dability and maintainability
___
Bug fix
___
- Refactor checkbox state management to fix delay issues
- Replace object spread with direct property mutation
- Add explicit return statements for better clarity
___
```mermaid
flowchart LR
A["Checkbox Click"] --> B["State Update"]
B --> C["Direct Property Mutation"]
C --> D["Immediate UI Response"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>TableComponent.tsx</strong><dd><code>Refactor checkbox state management for performance</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
app/components/TableComponent.tsx
<ul><li>Replace object …

Fix #1113 Fix delay in checkbox

---

app/api/auth/[...nextauth]/options.ts
app/api/auth/login/route.ts
package-lock.json
package.json

Enhancement
___
- Add REST API login endpoint for FalkorDB authentication
- Export utility functions for JWT token generation
- Add jose dependency for JWT handling
___
```mermaid
flowchart LR
A["Client Login Request"] --> B["POST /api/auth/login"]
B --> C["Validate Credentials"]
C --> D["Connect to FalkorDB"]
D --> E["Generate JWT Token"]
E --> F["Return Authentication Response"]
```
<tr>
<td>
<details>
<summary><strong>options.ts</strong><dd><code>Export authentication utility functions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Add Login for Rest Api

---

app/graph/Tutorial.tsx
app/graph/page.tsx
app/providers.tsx

… Remove unused tutorial import from graph page.
___
Enhancement
___
- Refactor tutorial component to use external state management
- Move tutorial initialization logic to providers layer
- Remove direct tutorial import from graph page
- Update tutorial styling with responsive padding
___
```mermaid
flowchart LR
A["Graph Page"] -- "removes direct import" --> B["Tutorial Component"]
C["Providers"] -- "manages state" --> B
C -- "initializes from localStorage" --> D["Tutorial State"]
B -- "receives props" --> D
```
<tr>
<td>
<details>
<summary><strong>Tutorial.tsx</strong><dd><code>Convert to …

Fix #1147 fix tutorial

---

package-lock.json
package.json

Other
___
- Update package version from 1.4.6 to 1.4.7
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Version bump to 1.4.7</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
- Updated version field from "1.4.6" to "1.4.7"
</details>
</td>
<td><a href="https://github.com/FalkorDB/falkordb-browser/pull/1164/files#diff-7ae45ad102eab …

Update version to 1.4.7 in package.json and package-lock.json
